import { Flashcard } from "./types";

const fallbackCards: Record<string, Flashcard[]> = {
  travel: [
    { id: 1, chinese: "厕所在哪里？", pinyin: "cèsuǒ zài nǎlǐ", english: "Where is the bathroom?" },
    { id: 2, chinese: "我迷路了", pinyin: "wǒ mílù le", english: "I'm lost" },
    { id: 3, chinese: "这个多少钱？", pinyin: "zhège duōshao qián", english: "How much is this?" },
    { id: 4, chinese: "我需要帮助", pinyin: "wǒ xūyào bāngzhù", english: "I need help" },
    { id: 5, chinese: "请慢一点说", pinyin: "qǐng màn yīdiǎn shuō", english: "Please speak slower" },
    { id: 6, chinese: "你好", pinyin: "nǐ hǎo", english: "Hello" },
    { id: 7, chinese: "谢谢", pinyin: "xièxiè", english: "Thank you" },
    { id: 8, chinese: "对不起", pinyin: "duìbuqǐ", english: "Excuse me / Sorry" },
    { id: 9, chinese: "我不懂", pinyin: "wǒ bù dǒng", english: "I don't understand" },
    { id: 10, chinese: "你会说英语吗？", pinyin: "nǐ huì shuō yīngyǔ ma", english: "Do you speak English?" },
  ],
  taxi: [
    { id: 1, chinese: "请带我去机场", pinyin: "qǐng dài wǒ qù jīchǎng", english: "Please take me to the airport" },
    { id: 2, chinese: "到那里要多久？", pinyin: "dào nàlǐ yào duōjiǔ", english: "How long will it take?" },
    { id: 3, chinese: "在这里停车", pinyin: "zài zhèlǐ tíngchē", english: "Stop here" },
    { id: 4, chinese: "多少钱？", pinyin: "duōshao qián", english: "How much?" },
    { id: 5, chinese: "请打开空调", pinyin: "qǐng dǎkāi kōngtiáo", english: "Please turn on the AC" },
    { id: 6, chinese: "我要去这个地址", pinyin: "wǒ yào qù zhège dìzhǐ", english: "I want to go to this address" },
    { id: 7, chinese: "请快一点", pinyin: "qǐng kuài yīdiǎn", english: "Please hurry" },
    { id: 8, chinese: "可以用信用卡吗？", pinyin: "kěyǐ yòng xìnyòngkǎ ma", english: "Can I pay by credit card?" },
    { id: 9, chinese: "请等一下", pinyin: "qǐng děng yīxià", english: "Please wait a moment" },
    { id: 10, chinese: "把我放在路口", pinyin: "bǎ wǒ fàng zài lùkǒu", english: "Drop me off at the corner" },
  ],
  "ordering-food": [
    { id: 1, chinese: "我要点菜", pinyin: "wǒ yào diǎn cài", english: "I'd like to order" },
    { id: 2, chinese: "这个是什么？", pinyin: "zhège shì shénme", english: "What is this?" },
    { id: 3, chinese: "我是素食者", pinyin: "wǒ shì sùshí zhě", english: "I'm vegetarian" },
    { id: 4, chinese: "不要辣的", pinyin: "bùyào là de", english: "No spicy please" },
    { id: 5, chinese: "可以买单吗？", pinyin: "kěyǐ mǎidān ma", english: "Can I get the check?" },
    { id: 6, chinese: "再来一份", pinyin: "zài lái yī fèn", english: "One more serving please" },
    { id: 7, chinese: "好吃！", pinyin: "hǎo chī", english: "Delicious!" },
    { id: 8, chinese: "有没有英文菜单？", pinyin: "yǒu méiyǒu yīngwén càidān", english: "Is there an English menu?" },
    { id: 9, chinese: "我对花生过敏", pinyin: "wǒ duì huāshēng guòmǐn", english: "I'm allergic to peanuts" },
    { id: 10, chinese: "请给我水", pinyin: "qǐng gěi wǒ shuǐ", english: "Please give me water" },
  ],
  dating: [
    { id: 1, chinese: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzì", english: "What's your name?" },
    { id: 2, chinese: "你真漂亮", pinyin: "nǐ zhēn piàoliang", english: "You're really beautiful" },
    { id: 3, chinese: "我可以请你喝杯咖啡吗？", pinyin: "wǒ kěyǐ qǐng nǐ hē bēi kāfēi ma", english: "Can I buy you a coffee?" },
    { id: 4, chinese: "你有男朋友吗？", pinyin: "nǐ yǒu nán péngyǒu ma", english: "Do you have a boyfriend?" },
    { id: 5, chinese: "我很喜欢你", pinyin: "wǒ hěn xǐhuān nǐ", english: "I really like you" },
    { id: 6, chinese: "我们可以再见面吗？", pinyin: "wǒmen kěyǐ zài jiànmiàn ma", english: "Can we meet again?" },
    { id: 7, chinese: "你在哪里工作？", pinyin: "nǐ zài nǎlǐ gōngzuò", english: "Where do you work?" },
    { id: 8, chinese: "这是我的电话号码", pinyin: "zhè shì wǒ de diànhuà hàomǎ", english: "This is my phone number" },
    { id: 9, chinese: "你喜欢做什么？", pinyin: "nǐ xǐhuān zuò shénme", english: "What do you like to do?" },
    { id: 10, chinese: "我很高兴认识你", pinyin: "wǒ hěn gāoxìng rènshì nǐ", english: "Nice to meet you" },
  ],
  business: [
    { id: 1, chinese: "我是来开会的", pinyin: "wǒ shì lái kāihuì de", english: "I'm here for a meeting" },
    { id: 2, chinese: "这是我的名片", pinyin: "zhè shì wǒ de míngpiàn", english: "This is my business card" },
    { id: 3, chinese: "我们可以合作吗？", pinyin: "wǒmen kěyǐ hézuò ma", english: "Can we work together?" },
    { id: 4, chinese: "请发给我报价单", pinyin: "qǐng fā gěi wǒ bàojiàdān", english: "Please send me a quote" },
    { id: 5, chinese: "我需要更多时间考虑", pinyin: "wǒ xūyào gèng duō shíjiān kǎolǜ", english: "I need more time to think" },
    { id: 6, chinese: "我们什么时候开始？", pinyin: "wǒmen shénme shíhòu kāishǐ", english: "When do we start?" },
    { id: 7, chinese: "这个价格可以谈吗？", pinyin: "zhège jiàgé kěyǐ tán ma", english: "Is the price negotiable?" },
    { id: 8, chinese: "我代表我的公司", pinyin: "wǒ dàibiǎo wǒ de gōngsī", english: "I represent my company" },
    { id: 9, chinese: "请签这份合同", pinyin: "qǐng qiān zhè fèn hétong", english: "Please sign this contract" },
    { id: 10, chinese: "我会回复您的邮件", pinyin: "wǒ huì huífù nín de yóujiàn", english: "I'll reply to your email" },
  ],
  education: [
    { id: 1, chinese: "我在学中文", pinyin: "wǒ zài xué zhōngwén", english: "I'm studying Chinese" },
    { id: 2, chinese: "请再说一遍", pinyin: "qǐng zài shuō yī biàn", english: "Please say it again" },
    { id: 3, chinese: "这个词是什么意思？", pinyin: "zhège cí shì shénme yìsi", english: "What does this word mean?" },
    { id: 4, chinese: "我要报名上课", pinyin: "wǒ yào bàomíng shàngkè", english: "I want to enroll in class" },
    { id: 5, chinese: "作业在哪里交？", pinyin: "zuòyè zài nǎlǐ jiāo", english: "Where do I submit the homework?" },
    { id: 6, chinese: "可以帮我翻译吗？", pinyin: "kěyǐ bāng wǒ fānyì ma", english: "Can you help me translate?" },
    { id: 7, chinese: "我不会写这个字", pinyin: "wǒ bù huì xiě zhège zì", english: "I don't know how to write this character" },
    { id: 8, chinese: "考试什么时候？", pinyin: "kǎoshì shénme shíhòu", english: "When is the exam?" },
    { id: 9, chinese: "我需要练习口语", pinyin: "wǒ xūyào liànxí kǒuyǔ", english: "I need to practice speaking" },
    { id: 10, chinese: "你是我的老师吗？", pinyin: "nǐ shì wǒ de lǎoshī ma", english: "Are you my teacher?" },
  ],
  shopping: [
    { id: 1, chinese: "这个多少钱？", pinyin: "zhège duōshao qián", english: "How much is this?" },
    { id: 2, chinese: "有没有打折？", pinyin: "yǒu méiyǒu dǎzhé", english: "Is there a discount?" },
    { id: 3, chinese: "我要试穿一下", pinyin: "wǒ yào shì chuān yīxià", english: "I want to try it on" },
    { id: 4, chinese: "有没有大号的？", pinyin: "yǒu méiyǒu dà hào de", english: "Do you have a larger size?" },
    { id: 5, chinese: "可以退货吗？", pinyin: "kěyǐ tuìhuò ma", english: "Can I return this?" },
    { id: 6, chinese: "我要这个", pinyin: "wǒ yào zhège", english: "I want this one" },
    { id: 7, chinese: "太贵了", pinyin: "tài guì le", english: "Too expensive" },
    { id: 8, chinese: "便宜一点可以吗？", pinyin: "piányí yīdiǎn kěyǐ ma", english: "Can you make it cheaper?" },
    { id: 9, chinese: "有没有其他颜色？", pinyin: "yǒu méiyǒu qítā yánsè", english: "Do you have other colors?" },
    { id: 10, chinese: "我用微信支付", pinyin: "wǒ yòng wēixìn zhīfù", english: "I'll pay with WeChat Pay" },
  ],
  home: [
    { id: 1, chinese: "请进", pinyin: "qǐng jìn", english: "Please come in" },
    { id: 2, chinese: "晚饭做好了", pinyin: "wǎnfàn zuò hǎo le", english: "Dinner is ready" },
    { id: 3, chinese: "把垃圾拿出去", pinyin: "bǎ lājī ná chūqù", english: "Take out the trash" },
    { id: 4, chinese: "今天谁做饭？", pinyin: "jīntiān shuí zuòfàn", english: "Who's cooking today?" },
    { id: 5, chinese: "能帮我一个忙吗？", pinyin: "néng bāng wǒ yī gè máng ma", english: "Can you do me a favor?" },
    { id: 6, chinese: "把电视关掉", pinyin: "bǎ diànshì guān diào", english: "Turn off the TV" },
    { id: 7, chinese: "我回来了", pinyin: "wǒ huí lái le", english: "I'm home" },
    { id: 8, chinese: "孩子们在哪里？", pinyin: "háizi men zài nǎlǐ", english: "Where are the kids?" },
    { id: 9, chinese: "我们需要买东西", pinyin: "wǒmen xūyào mǎi dōngxi", english: "We need to go shopping" },
    { id: 10, chinese: "今晚有什么计划？", pinyin: "jīnwǎn yǒu shénme jìhuà", english: "Any plans tonight?" },
  ],
};

export function getFallbackCards(topic: string, limit?: number): Flashcard[] {
  const cards = fallbackCards[topic] ?? fallbackCards.travel;
  if (!limit) return cards;
  return cards.slice(0, Math.max(1, limit));
}
