name: Build Mobile App

on:
  workflow_dispatch:   # manual button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g eas-cli
      - run: npm install

      - run: npx eas-cli whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - run: npx eas-cli build --platform all --non-interactive --no-wait --project-id eb4ac187-0d19-4b08-8276-3c8333ed1c4b
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}